# Generated by Django 4.0.4 on 2022-04-24 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=255)),
                ('mission_descriptions', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('status', models.BooleanField()),
                ('spy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSAKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=1024)),
                ('e', models.CharField(max_length=1024)),
                ('q', models.CharField(max_length=1024)),
                ('p', models.CharField(max_length=1024)),
                ('d', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=5)),
                ('code_name', models.CharField(max_length=15)),
                ('rsa_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spy.rsakey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=255)),
                ('mission_descriptions', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('status', models.BooleanField()),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spy.mission')),
                ('spy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
