# Generated by Django 4.0.4 on 2022-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0003_alter_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionadmin',
            name='status',
            field=models.CharField(max_length=8),
        ),
    ]
