# Generated by Django 4.0.4 on 2022-04-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0004_alter_missionadmin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_descriptions',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='missionadmin',
            name='mission_descriptions',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='missionadmin',
            name='mission_name',
            field=models.CharField(max_length=1024),
        ),
    ]
