# Generated by Django 4.0.4 on 2022-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0005_alter_mission_mission_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_descriptions',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_name',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='missionadmin',
            name='mission_descriptions',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='missionadmin',
            name='mission_name',
            field=models.BinaryField(),
        ),
    ]
